[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/auth"
  to = "/.netlify/functions/auth"
  status = 200

[[redirects]]
  from = "/api/visits"
  to = "/.netlify/functions/visits"
  status = 200
